{% set python_min = "3.10" %}
{% set name = "hydromt_delwaq" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hydromt_delwaq-{{ version }}.tar.gz
  sha256: ae6eee39dfa5a752338348e5e6b8638f2de1665fc338f2dabae64c95eaa4233b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit
    - pip
  run:
    - python >={{ python_min }}
    - hydromt >=0.9.1,<0.11
    - hydromt_wflow >=0.5.0,<0.9
    - geopandas >=0.10
    - numpy
    - pandas
    - pyproj
    - rasterio
    - scipy
    - shapely >=2.0.0
    - tqdm
    - xarray
    - xugrid >=0.14.3

test:
  imports:
    - hydromt_delwaq
  commands:
    - pip check
    - hydromt --models
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/hydromt_delwaq/
  summary: hydroMT plugin for DELWAQ models.
  dev_url: https://github.com/Deltares/hydromt_delwaq
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - FMSST
    - hboisgon
    - sibrenloos
