{% set name = "hydromt_delwaq" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hydromt_delwaq-{{ version }}.tar.gz
  sha256: 4f1909a7a1838a77d0f3bf70f896694a3bb5b012ba4e2a29229e941fe0b38d7d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - flit
    - pip
  run:
    - python >=3.10
    - hydromt >=0.9.1,<0.11
    - hydromt_wflow >=0.4.0
    - geopandas >=0.10
    - numpy <2
    - pandas
    - pyproj
    - rasterio
    - scipy
    - shapely >=2.0.0
    - tqdm
    - xarray
    - xugrid

test:
  imports:
    - hydromt_delwaq
  commands:
    - pip check
    - hydromt --models
  requires:
    - pip

about:
  home: https://pypi.org/project/hydromt_delwaq/
  summary: hydroMT plugin for DELWAQ models.
  dev_url: https://github.com/Deltares/hydromt_delwaq
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - deltares-service-account
    - hboisgon
    - sibrenloos
